{% set name = "p4p" %}
{% set version = "4.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mdavidsaver/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 024115fdd82f233034a7b972599af4d1e988fba33e0f0f2d65efc569780c9a14

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - epicscorelibs
    - numpy
    - pip
    - ply
    - setuptools
    - setuptools_dso
    - pvxslibs
  run:
    - python
    - cython
    - epicscorelibs
    - nose >=1.1.2
    - {{ pin_compatible('numpy') }}
    - ply
    - setuptools_dso
    - pvxslibs

test:
  imports:
    - p4p

about:
  home: http://github.com/mdavidsaver/p4p
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python bindings for the PVAccess network client and server.
  doc_url: https://mdavidsaver.github.io/p4p/
  dev_url: https://github.com/mdavidsaver/p4p

extra:
  recipe-maintainers:
    - jacquelinegarrahan
    - hhslepicka
