{% set name = "epix-hr-m-320k" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file:///sdf/group/lcls/ds/ana/sw/source_files/{{ name }}-{{ version }}.tar.gz
  sha256: 861a85b9006ef24e9340d2a39a44b96a44e8ede611da17fa19ff5156c7509a86
  patches:
    - setup.patch

build:
  skip: True  # [win or osx]
  noarch: python
  number: 1
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python

about:
  home: https://github.com/slaclab/epix-hr-m-320k
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Epix HR M 320k software and firmware'
  description: |
    firmware for Epix HR M 320k devices.
  doc_url: https://github.com/slaclab/epix-hr-m-320k
  dev_url: https://github.com/slaclab/epix-hr-m-320k

extra:
  recipe-maintainers:
    - valmar
    - chrisvam

