{% set name = "libfabric" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ofiwg/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: fb6b9deace1dda86dfa88b2d876516becd6e932e79e384763d634b92fec31082
  - path: ./ib_user_verbs.h

build:
  skip: True  # [win or osx]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libuuid') }}
    - {{ cdt('libuuid-devel') }}
    - make
    - cmake
    - autoconf
    - automake
    - libtool
  host:
    - libnl
    - rdma-core
  run:
    - libnl
    - rdma-core

about:
  home: https://ofiwg.github.io/libfabric/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: 'Library for the Open Fabrics Interfaces (OFI)'
  description: |
    OpenFabrics Interfaces (OFI) is a framework
    focused on exporting fabric communication
    services to applications. OFI is best described
    as a collection of libraries and applications
    used to export fabric services. The key
    components of OFI are: application interfaces,
    provider libraries, kernel services, daemons,
    and test applications. Libfabric is a core
    component of OFI. It is the library that defines
    and exports the user-space API of OFI, and is
    typically the only software that applications deal
    with directly. It works in conjunction with provider
    libraries, which are often integrated directly into
    libfabric.
  doc_url: https://ofiwg.github.io/libfabric/
  dev_url: https://github.com/ofiwg/libfabric

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
