{% set name = "fpzip" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LLNL/fpzip/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 248df7d84259e3feaa4c4797956b2a77c3fcd734e8f8fdc51ce171dcf4f0136c

build:
  skip: True  # [win or osx]
  number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - zlib
    - zstd
  run:
    - zlib
    - zstd

about:
  home: https://github.com/LLNL/fpzip
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Lossless and lossy compression o floating-point arrays'
  description: |
     fpzip is a library and command-line utility for lossless and
     optionally lossy compression of 2D and 3D floating-point arrays.
     fpzip assumes spatially correlated scalar-valued data, such as
     regularly sampled continuous functions, and is not suitable for
     compressing unstructured streams of floating-point numbers. In
     lossy mode, fpzip discards some number of least significant
     mantissa bits and losslessly compresses the result. fpzip currently
     supports IEEE-754 single (32-bit) and double (64-bit) precision
     floating-point data. fpzip is written in C++ but has a C compatible
     API that can be called from C and other languages. It conforms to
     the C++98 and C89 language standards.
  doc_url: https://github.com/LLNL/fpzip
  dev_url: https://github.com/LLNL/fpzip

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
